alertmanager:
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 0.14.0
  namespace: dev
  image:
    tag: v0.14.0
  replicas: 3
  externalUrl: http://127.0.0.1:9093
  kubernetesIoZone: us-west-2a
  service:
    forceSslRedirect: "true"
    ingressClass: internal-ingress
    annotations:
    expose: "true"
  secrets:
    alertManagerYaml:
      Z2xvYmFsOgoKICByZXNvbHZlX3RpbWVvdXQ6IDVtCgogIHNsYWNrX2FwaV91cmw6ICdodHRwczovL2hvb2tzLnNsYWNrLmNvbS9zZXJ2aWNlcy9UNlA1UFMyVjgvQjlBS0NHOUE0L1U4WjhRNzdBakxuV1UwOWN5d0I0TlRIaScKCnRlbXBsYXRlczoKCi0gJy9ldGMvYWxlcnRtYW5hZ2VyL3RlbXBsYXRlLyoudG1wbCcKCnJvdXRlOgoKICBncm91cF9ieTogWydhbGVydG5hbWUnLCAnY2x1c3RlcicsICdzZXJ2aWNlJ10KCiAgZ3JvdXBfd2FpdDogMzBzCgogIGdyb3VwX2ludGVydmFsOiA1bQoKICByZXBlYXRfaW50ZXJ2YWw6IDFoCgogIHJlY2VpdmVyOiBkZWZhdWx0LXJlY2VpdmVyCgogIHJvdXRlczoKCiAgLSBtYXRjaDoKCiAgICAgIGFsZXJ0bmFtZTogRGVhZE1hbnNTd2l0Y2gKCiAgICByZWNlaXZlcjogJ251bGwnCgppbmhpYml0X3J1bGVzOgoKLSBzb3VyY2VfbWF0Y2g6CgogICAgc2V2ZXJpdHk6ICdjcml0aWNhbCcKCiAgdGFyZ2V0X21hdGNoOgoKICAgIHNldmVyaXR5OiAnd2FybmluZycKCiAgIyBBcHBseSBpbmhpYml0aW9uIGlmIHRoZSBhbGVydG5hbWUgaXMgdGhlIHNhbWUuCgogIGVxdWFsOiBbJ2FsZXJ0bmFtZScsICdjbHVzdGVyJywgJ3NlcnZpY2UnXQoKcmVjZWl2ZXJzOgoKLSBuYW1lOiAnZGVmYXVsdC1yZWNlaXZlcicKCiAgc2xhY2tfY29uZmlnczoKCiAgLSBjaGFubmVsOiAnI2Rldi1ub3RpZmljYXRpb25zJwoKICAgIHRpdGxlOiAnW3t7IC5TdGF0dXMgfCB0b1VwcGVyIH19e3sgaWYgZXEgLlN0YXR1cyAiZmlyaW5nIiB9fTp7eyAuQWxlcnRzLkZpcmluZyB8IGxlbiB9fXt7IGVuZCB9fV0gUHJvbWV0aGV1cyBFdmVudCBOb3RpZmljYXRpb24nCgogICAgdGl0bGVfbGluazogfAoKICAgICAgaHR0cHM6Ly9hbGVydG1hbmFnZXItbWFpbi5tb25pdG9yaW5nLnN0YWNrYXRvci5jb20KCiAgICB0ZXh0OiA+LQoKICAgICAgICB7eyByYW5nZSAuQWxlcnRzIH19CgogICAgICAgICAgICpBbGVydDoqIHt7IC5Bbm5vdGF0aW9ucy5zdW1tYXJ5IH19IC0gYHt7IC5MYWJlbHMuc2V2ZXJpdHkgfX1gCgogICAgICAgICAgKkRlc2NyaXB0aW9uOioge3sgLkFubm90YXRpb25zLmRlc2NyaXB0aW9uIH19CgogICAgICAgICAgKkdyYXBoOiogPHt7IC5HZW5lcmF0b3JVUkwgfX18OmNoYXJ0X3dpdGhfdXB3YXJkc190cmVuZDo+ICpSdW5ib29rOiogPHt7IC5Bbm5vdGF0aW9ucy5ydW5ib29rIH19fDpzcGlyYWxfbm90ZV9wYWQ6PgoKICAgICAgICAgICpEZXRhaWxzOioKCiAgICAgICAgICB7eyByYW5nZSAuTGFiZWxzLlNvcnRlZFBhaXJzIH19ICp7eyAuTmFtZSB9fToqIGB7eyAuVmFsdWUgfX1gCgogICAgICAgICAge3sgZW5kIH19CgogICAgICAgIHt7IGVuZCB9fQoKICAgIHNlbmRfcmVzb2x2ZWQ6IHRydWUKCi0gbmFtZTogJ251bGwnCgo=
