apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: main
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  spec:
  replicas: {{ .Values.alertmanager.replicas }}
  version: {{ .Values.alertmanager.image.tag }}
  externalUrl: {{ .Values.alertmanager.externalUrl }}
  nodeSelector:
    failure-domain.beta.kubernetes.io/zone: {{ .Values.alertmanager.kubernetesIoZone }}
