apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: main
  labels:
{{ include "alertmanager.labels.stakater" . | indent 4 }}
{{ include "alertmanager.labels.chart" . | indent 4 }}
spec:
  replicas: {{ .Values.alertmanager.replicas }}
  version: {{ .Values.alertmanager.image.tag }}
  externalUrl: {{ .Values.alertmanager.externalUrl }}
  alertmanager: {{ .Values.alertmanager.alertmanagerMain }}
  securityContext: {}
  {{- if .Values.alertmanager.nodeSelector }}
  nodeSelector:
    {{ .Values.alertmanager.nodeSelector.key }}: {{ .Values.alertmanager.nodeSelector.value }}
  {{- end }}
